package com.zcw.chatai.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import com.zcw.chatai.data.prefs.ThemeFamily

private val ChatGptLightChatColors = ChatColors(
    canvas = GptWhite,
    surfaceSoft = GptSurface,
    surfaceCard = GptSurface,
    surfaceCreamStrong = GptSurfaceStrong,
    hairline = GptBorder,
    hairlineSoft = GptBorderSoft,
    codeBackground = GptCodeBackground,
    codeOnBackground = GptDarkText,
    codeHeaderText = GptMutedSoft,
    codeButtonBackground = GptCodeButtonBackground,
    bubbleUser = GptSurface,
    bubbleUserText = GptBlack,
    chipBackground = GptSurface,
    accentTeal = GptSuccess,
    accentAmber = GptAmber,
    success = GptSuccess,
    warning = GptAmber,
)

private val ChatGptDarkChatColors = ChatColors(
    canvas = GptDarkCanvas,
    surfaceSoft = GptDarkSunken,
    surfaceCard = GptDarkRaised,
    surfaceCreamStrong = GptDarkHigh,
    hairline = GptDarkBorder,
    hairlineSoft = GptDarkRaised,
    codeBackground = GptCodeBackground,
    codeOnBackground = GptDarkText,
    codeHeaderText = GptDarkSoft,
    codeButtonBackground = GptCodeButtonBackground,
    bubbleUser = GptDarkRaised,
    bubbleUserText = GptDarkText,
    chipBackground = GptDarkRaised,
    accentTeal = GptSuccess,
    accentAmber = GptAmber,
    success = GptSuccess,
    warning = GptAmber,
)

private val ChatGptLightScheme = lightColorScheme(
    primary = GptBlack,
    onPrimary = GptWhite,
    primaryContainer = GptSurface,
    onPrimaryContainer = GptBlack,
    inversePrimary = GptBodyText,
    secondary = GptBodyText,
    onSecondary = GptWhite,
    secondaryContainer = GptSurface,
    onSecondaryContainer = GptBlack,
    tertiary = GptAmber,
    onTertiary = GptBlack,
    tertiaryContainer = GptSurface,
    onTertiaryContainer = GptBlack,
    background = GptWhite,
    onBackground = GptBlack,
    surface = GptWhite,
    onSurface = GptBlack,
    surfaceVariant = GptSurface,
    onSurfaceVariant = GptMuted,
    surfaceTint = GptBlack,
    inverseSurface = GptBlack,
    inverseOnSurface = GptWhite,
    error = GptRed,
    onError = GptWhite,
    errorContainer = GptRedSoft,
    onErrorContainer = GptRed,
    outline = GptBorder,
    outlineVariant = GptBorderSoft,
    scrim = GptBlack,
    surfaceBright = GptWhite,
    surfaceDim = GptSurface,
    surfaceContainerLowest = GptWhite,
    surfaceContainerLow = GptSurface,
    surfaceContainer = GptSurface,
    surfaceContainerHigh = GptSurfaceStrong,
    surfaceContainerHighest = GptSurfaceStrong,
)

private val ChatGptDarkScheme = darkColorScheme(
    primary = GptWhite,
    onPrimary = GptBlack,
    primaryContainer = GptDarkHigh,
    onPrimaryContainer = GptDarkText,
    inversePrimary = GptDarkText,
    secondary = GptDarkMuted,
    onSecondary = GptDarkCanvas,
    secondaryContainer = GptDarkHigh,
    onSecondaryContainer = GptDarkText,
    tertiary = GptAmber,
    onTertiary = GptBlack,
    tertiaryContainer = GptDarkAmberContainer,
    onTertiaryContainer = GptDarkOnAmberContainer,
    background = GptDarkCanvas,
    onBackground = GptDarkText,
    surface = GptDarkCanvas,
    onSurface = GptDarkText,
    surfaceVariant = GptDarkRaised,
    onSurfaceVariant = GptDarkMuted,
    surfaceTint = GptWhite,
    inverseSurface = GptDarkText,
    inverseOnSurface = GptDarkCanvas,
    error = GptDarkError,
    onError = GptDarkOnError,
    errorContainer = GptDarkErrorContainer,
    onErrorContainer = GptDarkError,
    outline = GptDarkBorder,
    outlineVariant = GptDarkBorder,
    scrim = GptDarkSunken,
    surfaceBright = GptDarkHigh,
    surfaceDim = GptDarkCanvas,
    surfaceContainerLowest = GptDarkCanvas,
    surfaceContainerLow = GptDarkSunken,
    surfaceContainer = GptDarkRaised,
    surfaceContainerHigh = GptDarkRaised,
    surfaceContainerHighest = GptDarkHigh,
)

/** OpenAI / ChatGPT：单色黑/白/灰 chrome + 语义状态色；正文无衬线。 */
val ChatGptTheme = AppTheme(
    family = ThemeFamily.CHATGPT,
    displayName = "ChatGPT",
    light = ThemePalette(ChatGptLightChatColors, ChatGptLightScheme),
    dark = ThemePalette(ChatGptDarkChatColors, ChatGptDarkScheme),
    typography = SansTypography,
    chatTypography = ChatTypography.ChatGpt,
)
