package com.zcw.chatai.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import com.zcw.chatai.data.prefs.ThemeFamily

private val ClaudeLightChatColors = ChatColors(
    canvas = Canvas,
    surfaceSoft = SurfaceSoft,
    surfaceCard = SurfaceCard,
    surfaceCreamStrong = SurfaceCreamStrong,
    hairline = Hairline,
    hairlineSoft = HairlineSoft,
    codeBackground = SurfaceDark,
    codeOnBackground = OnDark,
    codeHeaderText = OnDarkSoft,
    codeButtonBackground = SurfaceDarkElevated,
    bubbleUser = SurfaceCard,
    bubbleUserText = Ink,
    chipBackground = SurfaceSoft,
    accentTeal = AccentTeal,
    accentAmber = AccentAmber,
    success = Success,
    warning = Warning,
)

private val ClaudeDarkChatColors = ChatColors(
    canvas = DarkCanvas,
    surfaceSoft = DarkSurface,
    surfaceCard = DarkSurfaceElevated,
    surfaceCreamStrong = DarkSurfaceHighest,
    hairline = DarkHairline,
    hairlineSoft = DarkHairlineSoft,
    codeBackground = DarkSurfaceLowest,
    codeOnBackground = OnDark,
    codeHeaderText = OnDarkSoft,
    codeButtonBackground = DarkSurfaceElevated,
    bubbleUser = DarkSurfaceElevated,
    bubbleUserText = OnDark,
    chipBackground = DarkSurfaceHighest,
    accentTeal = AccentTeal,
    accentAmber = AccentAmber,
    success = Success,
    warning = Warning,
)

private val ClaudeLightScheme = lightColorScheme(
    primary = Coral,
    onPrimary = OnPrimary,
    primaryContainer = SurfaceCreamStrong,
    onPrimaryContainer = Ink,
    inversePrimary = CoralActive,
    secondary = AccentTeal,
    onSecondary = OnPrimary,
    secondaryContainer = SurfaceCreamStrong,
    onSecondaryContainer = Ink,
    tertiary = AccentAmber,
    onTertiary = Ink,
    tertiaryContainer = SurfaceCard,
    onTertiaryContainer = Ink,
    background = Canvas,
    onBackground = Ink,
    surface = Canvas,
    onSurface = Ink,
    surfaceVariant = SurfaceSoft,
    onSurfaceVariant = Muted,
    surfaceTint = Coral,
    inverseSurface = SurfaceDark,
    inverseOnSurface = OnDark,
    error = ErrorRed,
    onError = OnPrimary,
    errorContainer = SurfaceCreamStrong,
    onErrorContainer = ErrorRed,
    outline = Hairline,
    outlineVariant = HairlineSoft,
    scrim = Ink,
    surfaceBright = Canvas,
    surfaceDim = SurfaceSoft,
    surfaceContainerLowest = Canvas,
    surfaceContainerLow = SurfaceSoft,
    surfaceContainer = SurfaceCard,
    surfaceContainerHigh = SurfaceCreamStrong,
    surfaceContainerHighest = SurfaceCreamStrong,
)

private val ClaudeDarkScheme = darkColorScheme(
    primary = Coral,
    onPrimary = OnPrimary,
    primaryContainer = DarkCoralContainer,
    onPrimaryContainer = DarkOnCoralContainer,
    inversePrimary = CoralActive,
    secondary = AccentTeal,
    onSecondary = DarkOnTealContainer,
    secondaryContainer = DarkTealContainer,
    onSecondaryContainer = DarkOnTealContainer,
    tertiary = AccentAmber,
    onTertiary = DarkOnAmberContainer,
    tertiaryContainer = DarkAmberContainer,
    onTertiaryContainer = DarkOnAmberContainer,
    background = DarkCanvas,
    onBackground = OnDark,
    surface = DarkSurface,
    onSurface = OnDark,
    surfaceVariant = DarkSurfaceElevated,
    onSurfaceVariant = OnDarkSoft,
    surfaceTint = Coral,
    inverseSurface = OnDark,
    inverseOnSurface = DarkCanvas,
    error = DarkError,
    onError = DarkOnError,
    errorContainer = DarkCoralContainer,
    onErrorContainer = DarkError,
    outline = DarkOutline,
    outlineVariant = DarkHairline,
    scrim = DarkSurfaceLowest,
    surfaceBright = DarkSurfaceHighest,
    surfaceDim = DarkCanvas,
    surfaceContainerLowest = DarkSurfaceLowest,
    surfaceContainerLow = DarkCanvas,
    surfaceContainer = DarkSurface,
    surfaceContainerHigh = DarkSurfaceElevated,
    surfaceContainerHighest = DarkSurfaceHighest,
)

/** Anthropic / Claude：暖奶油画布 + 珊瑚 CTA + 深色产品面；正文衬线。 */
val ClaudeTheme = AppTheme(
    family = ThemeFamily.CLAUDE,
    displayName = "Claude",
    light = ThemePalette(ClaudeLightChatColors, ClaudeLightScheme),
    dark = ThemePalette(ClaudeDarkChatColors, ClaudeDarkScheme),
    typography = SerifTypography,
    chatTypography = ChatTypography.Default,
)
